/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Inventarios;

import ClassAngels.SucursalUtil;
import ClassAngels.TextAreaRenderer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author it
 */
public class InventarioDiario extends javax.swing.JPanel {

    String Fecha;

    /**
     * Creates new form InventarioDiario
     */
    public InventarioDiario() {
        initComponents();
    }

    private void ListarProductosSolicitados(int tipo) throws Exception {
        ArrayList<ConsultaProductos> result = ListarUpdate.ListarProductos(Fecha,SucursalUtil.obtenerSucursal(),tipo);
        RecargarTabla(result);
    }

    private void RecargarTabla(ArrayList<ConsultaProductos> list) {
        Object[][] datos = new Object[list.size()][4];
        int i = 0;
        for (ConsultaProductos t : list) {
            datos[i][0] = t.getCODIGO();
            datos[i][1] = t.getDESCRIPCION();
            datos[i][2] = t.getCANTIDAD();
            datos[i][3] = t.getMEDIDA();

            i++;
        }

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{"CODIGO", "DESCRIPCION", "CANTIDAD", "MEDIDA"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2; // Solo se puede editar CANTIDAD
            }
        };

        ListaPro.setModel(model);
        ListaPro.getColumnModel().getColumn(1).setCellRenderer(new TextAreaRenderer());
        ListaPro.getColumnModel().getColumn(0).setPreferredWidth(-20);
        ListaPro.getColumnModel().getColumn(1).setPreferredWidth(255);
        ListaPro.getColumnModel().getColumn(2).setPreferredWidth(55);

        // Aquí se agrega el listener para detectar edición
        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE && e.getColumn() == 2) {
                    int row = e.getFirstRow();
                    int modelRow = ListaPro.convertRowIndexToModel(row);
                    int codigo = Integer.parseInt(
                            String.valueOf(model.getValueAt(modelRow, 0))
                    );
                    double cantidadRaw = Double.parseDouble(
                            String.valueOf(model.getValueAt(modelRow, 2))
                    );
                    double cantidad = Math.round(cantidadRaw * 100.0) / 100.0;

                   // int id_pedido = Integer.parseInt(NoPedido.getText());
                    System.out.println(codigo+"--"+cantidad+"--"+Fecha+"--"+SucursalUtil.obtenerSucursal());
                  ListarUpdate.actualizarCantidad(codigo,cantidad,Fecha,SucursalUtil.obtenerSucursal());//cantidad,codigo,fecha
                }
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPro = new javax.swing.JTable();
        Fe = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        ListaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "UNIDAD MEDIDA"
            }
        ));
        jScrollPane1.setViewportView(ListaPro);

        jButton2.setText("LISTAR BEBIDAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("LISTAR COMIDA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Fe, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Fe.getDate() != null) {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Fecha = df.format(Fe.getDate());
            try {
                ListarProductosSolicitados(1);
            } catch (Exception ex) {
                Logger.getLogger(InventarioDiario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE UNA FECHA...");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (Fe.getDate() != null) {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Fecha = df.format(Fe.getDate());
            try {
                ListarProductosSolicitados(2);
            } catch (Exception ex) {
                Logger.getLogger(InventarioDiario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE UNA FECHA...");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fe;
    private javax.swing.JTable ListaPro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
