/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Meseros;

import Inicio.*;
import AdministradorAngels.Contraseña;
import AdministradorAngels.Inventario;
import BDclass.BDConexion;
import BDclass.BDOrdenes;
import ClassAngels.OrdenesClass;
import FELclass.Token;
import Pedidos.AceptarPedido;
import Pedidos.InicioPedido;
import com.google.gson.Gson;
import com.google.gson.JsonSyntaxException;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
//import com.mysql.cj.xdevapi.Client;
//mport jakarta.ws.rs.client.ClientBuilder;
//import jakarta.ws.rs.client.Entity;
//import jakarta.ws.rs.client.Invocation;
//import jakarta.ws.rs.client.WebTarget;
import java.awt.Image;
import java.awt.event.ComponentEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//import okhttp3.Response;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;


/**
 *
 * @author jluis
 */
public class OrdenesMeseros extends javax.swing.JFrame {
   int noorden;
    String Token;
    String FechaExp;
   
    /**
     * Creates new form Ordenes
     */
    public OrdenesMeseros() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }
        initComponents();
        //token();
        imagen();
        
        this.setExtendedState(MAXIMIZED_BOTH);
         
        
        setLayout(new BorderLayout());
        add(jPanel1, BorderLayout.CENTER);
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 20; // Columna 0
        gbc.gridy = 0; // Fila 0
        jPanel1.add(NEWORDER,gbc);
        
        GridBagConstraints gbc1 = new GridBagConstraints();
        gbc1.gridx = 20; // Columna 0
        gbc1.gridy = 110; // Fila 0
        jPanel1.add(MESAS,gbc1);
        //setLocationRelativeTo(null);
        
        imagen();
    }
    
    
    public void crear() {

        try {

            OrdenesClass p = new OrdenesClass();
            BDOrdenes.InsertarPedido(p);
            noorden = p.getIdregresoPedido();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        //System.out.println("ID ="+id_pedido);
      

    }
    
    private void imagen() {

        try {
            ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Iconos/angels.png"));
            Image imgEscalada = imgIcon.getImage().getScaledInstance(imagen.getWidth(),
                    imagen.getHeight(), Image.SCALE_SMOOTH);
            Icon iconoEscalado = new ImageIcon(imgEscalada);
            imagen.setIcon(iconoEscalado);
        } catch (Exception e) {
            
            System.out.println("ERRROR IMAGEN "+e);
            JOptionPane.showMessageDialog(null, "ERROR + "+e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        NEWORDER = new ClassAngels.PanelRound();
        nueva = new javax.swing.JLabel();
        MESAS = new ClassAngels.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 643));

        NEWORDER.setBackground(new java.awt.Color(153, 255, 153));
        NEWORDER.setRoundBottomLeft(20);
        NEWORDER.setRoundBottomRight(20);
        NEWORDER.setRoundTopLeft(20);
        NEWORDER.setRoundTopRight(20);

        nueva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nueva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nueva.setText("NUEVA ORDEN");
        nueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NEWORDERLayout = new javax.swing.GroupLayout(NEWORDER);
        NEWORDER.setLayout(NEWORDERLayout);
        NEWORDERLayout.setHorizontalGroup(
            NEWORDERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nueva, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        NEWORDERLayout.setVerticalGroup(
            NEWORDERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nueva, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        MESAS.setBackground(new java.awt.Color(153, 255, 153));
        MESAS.setPreferredSize(new java.awt.Dimension(201, 83));
        MESAS.setRoundBottomLeft(20);
        MESAS.setRoundBottomRight(20);
        MESAS.setRoundTopLeft(20);
        MESAS.setRoundTopRight(20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MESAS");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MESASLayout = new javax.swing.GroupLayout(MESAS);
        MESAS.setLayout(MESASLayout);
        MESASLayout.setHorizontalGroup(
            MESASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        MESASLayout.setVerticalGroup(
            MESASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        imagen.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NEWORDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MESAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(378, 378, 378)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NEWORDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MESAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaMouseClicked
         crear();
         MesasMeseros F = new MesasMeseros(noorden);
         F.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nuevaMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       MesasSeguimientoMeseros F = new MesasSeguimientoMeseros();
        F.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

      private void token(){
         // System.out.println("llega token");
       String res = "";
       //String URL = "https://felgttestaws.digifact.com.gt/gt.com.apinuc/api/login/get_token";
       String URL = "https://felgtaws.digifact.com.gt/gt.com.apinuc/api/login/get_token";
        
        try {
            Client client = ClientBuilder.newClient();
            WebTarget target = client.target(URL );
            Invocation.Builder solicitud = target.request();
            Token req = new Token();
            req.setUsername("GT.000120011662.120011662");//NIT EMPRESA y USUARIO DIGIFAC
            req.setPassword("Factur4$Fel");//CONTRASEÑA DIGIFAC
            Gson gson = new Gson();
            String jsonString = gson.toJson(req);
            Response post = solicitud.post(Entity.json(jsonString));
            String resJson = post.readEntity(String.class);
            res = resJson;
            String fichero = "";
            fichero = resJson;
            Properties properties = gson.fromJson(fichero, Properties.class);
            Token = (String) properties.get("Token");
            FechaExp = (String) properties.get("expira_en");
        } catch (JsonSyntaxException e) {
            System.out.println("ERROR" );res = e.toString();
        }
    
        BDConexion conecta = new BDConexion();
        Connection con = conecta.getConexion();
        PreparedStatement sm = null;
        try {
            sm = con.prepareStatement("update token set Token = '"+Token+"',fecha = '"+FechaExp+"' where idToken = 1");
            sm.executeUpdate();
            con.close();
            sm.close();
        } catch (SQLException ex) {
            System.out.println("ERROR =" + ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenesMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenesMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenesMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenesMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenesMeseros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ClassAngels.PanelRound MESAS;
    private ClassAngels.PanelRound NEWORDER;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel nueva;
    // End of variables declaration//GEN-END:variables
}
